### ISSUE TITLE
PHANTOMJS2_DOWNLOAD_URL won't install on Windows

### ISSUE THREAD

**Issue by cherrydev** [gskachkov/phantomjs2#12]
When setting the variable to an official release package such as https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-windows.zip, it fails to install.

```
Download already available at C:\Users\acherry\AppData\Local\Temp\phantomjs\phantomjs-2.0.0-windows.zip
Extracting zip contents
Removing C:\Users\acherry\devpath\node_modules\karma-phantomjs2-launcher\node_modules\phantomjs2-ext\lib\phantom
Could not find extracted file [ 'phantomjs-2.0.0-windows' ]
Phantom installation failed [Error: Could not find extracted file] Error: Could not find extracted file
    at Promise._successFn (C:\Users\acherry\devpath\node_modules\karma-phantomjs2-launcher\node_modules\phantomjs2-ext\install.js:348:11)
    at nextTickCallback (C:\Users\acherry\devpath\node_modules\karma-phantomjs2-launcher\node_modules\phantomjs2-ext\node_modules\kew\kew.js:47:28)
    at process._tickCallback (node.js:355:11)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma-phantomjs2-launcher" "--savDev"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2-ext@0.1.0 install: `node install.js`
npm ERR! Exit status 1
```

**Comment by rodoabad** [comment]
Same.

```
D:\Web\GitHub\finance-calculators>npm install phantomjs2
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Applications\\nodejs\\node.exe" "C:\\Users\\rodoabad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs2"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.0
npm ERR! path D:\Web\GitHub\finance-calculators\node_modules\phantomjs2\lib\phantomjs\bin\phantomjs
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\Web\GitHub\finance-calculators\node_modules\phantomjs2\lib\phantomjs\bin\phantomjs'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Web\GitHub\finance-calculators\npm-debug.log

D:\Web\GitHub\finance-calculators>

```

**Comment by zenopopovici** [comment]
Same.

```
npm ERR! phantomjs2-ext@0.2.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2-ext@0.2.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs2-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs2-ext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs2-ext
npm ERR! There is likely additional logging output above.
```
