### ISSUE TITLE
TLS errors trying to install

### ISSUE THREAD

**Issue by chrylis** [gskachkov/phantomjs2#9]
When trying to install on Arch Linux, I'm getting a TLS error (note also that the report URL hasn't been updated from the upstream this package was forked from):

```
PhantomJS detected, but wrong version 2.0.0 @ /usr/bin/phantomjs.
Downloading https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-u1404-x86_64.zip
Saving to /tmp/phantomjs/phantomjs-2.0.0-20141016-u1404-x86_64.zip
Receiving...

Error making request.
Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN EPACKAGEJSON @artsquare/gallery-html-resources@0.0.1 No license field.
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "phantomjs2-ext"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2-ext@0.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2-ext@0.1.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2-ext
npm ERR! There is likely additional logging output above.
```

The log file doesn't appear to have anything else related to this package, just that error. I'm using Node 4.1.2 and NPM 3.3.6.

**Comment by gskachkov** [comment]
I didn't check my package on Arch Linux only on Mac/Ubuntu/Win, but at first look to the log this issue is not related to the issue with Phantomjs package. According to log it can download file over TLS(HTTPS) protocol
Possible some additional configuration is required for ArchLinux, for instance. Could you please take look to the following url and check if it your case 
https://bbs.archlinux.org/viewtopic.php?id=155255
http://unix.stackexchange.com/questions/93203/how-do-i-deal-with-a-certificate-based-transparent-proxy-in-arch-linux

**Comment by gskachkov** [comment]
Also Could you please take a look to readme of this package? There is described additional configuration of npm to prevent ssl errors
 `npm set strict-ssl false`

**Comment by francisoud** [comment]
Got the same issue under windows. It wasn't npm fault but my corporate proxy messing with ssl headers.
adding a `.npmrc` with `strict-ssl=false` fixed it.

**Comment by Veske** [comment]
Setting strict-ssl false is just arrogant or even plain retarded way to solve such issues. Please do care that your dependencies are actually downloaded through a safe channel.

**Comment by francisoud** [comment]
@Veske I agree... unless a broken/misconfigured enterprise proxy/sso (f5/siteminder in my case) mess up the ssl headers and you gave up asking the guys in charge of it to fix it... because they think it will broke some other hacks people add to put into place to workaround the problem.
